apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: webstone
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON *.* TO 'hohyun'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
