apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-74
  namespace: webstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-74
  template:
    metadata:
      labels:
        app: php-74
    spec:
      containers:
        - env:
            - name: NEW_GID
              value: "1000"
            - name: NEW_UID
              value: "1000"
          #image: devilbox/php-fpm:7.4-prod
          image: ghcr.io/hohyun/php-fpm-ffmpeg:7.4
          name: php-74
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/www/default/htdocs
              name: webstone-volume
      restartPolicy: Always
      volumes:
        - name: webstone-volume
          hostPath:
            path: /home/hohyun/Projects/webstone/htdocs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: php-74-svc
  namespace: webstone
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: php-74
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2
  namespace: webstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
        - env:
            - name: MAIN_VHOST_BACKEND
              value: conf:phpfpm:tcp:php-74:9000
            - name: NEW_GID
              value: "1000"
            - name: NEW_UID
              value: "1000"
            - name: TIMEZONE
              value: Asia/Seoul
          image: devilbox/apache-2.2
          imagePullPolicy: ""
          name: apache2
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/default/htdocs
              name: webstone-volume
      restartPolicy: Always
      volumes:
        - name: webstone-volume
          hostPath:
            path: /home/hohyun/Projects/webstone/htdocs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: apache2-svc
  namespace: webstone
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: apache2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webstone-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
  namespace: webstone
spec:
  ingressClassName: nginx
  rules:
    - host: webstone.newchunk.kr
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: apache2-svc
              port:
                number: 80
  tls:
    - hosts:
      - webstone.newchunk.kr
      secretName: letsencrypt-webstone-app
