apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: php-74
  name: php-74
  namespace: webstone
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php-74
  template:
    metadata:
      labels:
        io.kompose.service: php-74
    spec:
      containers:
        - env:
            - name: NEW_GID
              value: "1000"
            - name: NEW_UID
              value: "1000"
          #image: devilbox/php-fpm:7.4-prod
          image: ghcr.io/hohyun/php-fpm-ffmpeg:7.4
          name: php-74
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/www/default/htdocs
              name: webstoneeng-volume
      restartPolicy: Always
      volumes:
        - name: webstoneeng-volume
          hostPath:
            path: /home/hohyun/Projects/webstone/htdocs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: php-74
  name: php-74
  namespace: webstone
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: php-74
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: apache-php74
  name: apache-php74
  namespace: webstone
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apache-php74
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: apache-php74
    spec:
      containers:
        - env:
            - name: MAIN_VHOST_BACKEND
              value: conf:phpfpm:tcp:php-74:9000
            - name: NEW_GID
              value: "1000"
            - name: NEW_UID
              value: "1000"
            - name: TIMEZONE
              value: Asia/Seoul
          image: devilbox/apache-2.2
          imagePullPolicy: ""
          name: apache-php74
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/default/htdocs
              name: webstone-volume
      restartPolicy: Always
      volumes:
        - name: webstone-volume
          hostPath:
            path: /home/hohyun/Projects/webstone/htdocs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: apache-php74
  name: apache-php74
  namespace: webstone
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  selector:
    io.kompose.service: apache-php74
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webstone-ingress
  namespace: webstone
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - www.webstonetest.com
      secretName: my-selfsigned-ca
  rules:
    - host: www.webstonetest.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache-php74
                port:
                  number: 8081
